"""
T58 Trading — Prop Algo Backtester
Entry point.

Usage:
    python -m app.main                 # launch desktop GUI
    python -m app.main --cli --csv data/examples/EURUSD_5M_sample.csv
                                        # run the full pipeline headlessly
                                        # (useful on machines without a display,
                                        # and for scripted/CI runs)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from app.backtest.engine import run_backtest, run_holdout_comparison
from app.backtest.risk import RiskConfig
from app.data.importer import import_csv
from app.data.storage import list_stored_datasets, store_csv_path
from app.monte_carlo.engine import MonteCarloConfig, run_monte_carlo
from app.optimize.parameter_space import RefinementError
from app.optimize.refinement import RefinementConfig, run_iterative_refinement
from app.prop.simulator import PropRules, simulate_account
from app.reports.generator import generate_full_report
from app.reports.refinement_report import generate_refinement_report
from app.strategy.manual import ManualStrategy
from app.ui.main_window import launch

DEFAULT_MANUAL_STRATEGY = {
    "name": "SMA 20/50 Cross",
    "indicators": [
        {"type": "sma", "period": 20, "column": "close", "as": "sma_fast"},
        {"type": "sma", "period": 50, "column": "close", "as": "sma_slow"},
    ],
    "long_entry": "sma_fast > sma_slow",
    "long_exit": "sma_fast < sma_slow",
    "short_entry": "sma_fast < sma_slow",
    "short_exit": "sma_fast > sma_slow",
    "stop_loss_pips": 20,
    "take_profit_pips": 40,
}


def _resolve_default_csv() -> str:
    """Prefer a dataset already stored in data/raw/ over the bundled example."""
    stored = list_stored_datasets()
    if stored:
        return str(stored[0].path)  # most recently added
    return "data/examples/EURUSD_5M_sample.csv"


def run_cli(
    csv_path: str | None,
    n_sims: int,
    output_dir: str,
    refine: bool = False,
    refine_population: int = 10,
    refine_generations: int = 5,
    refine_metric: str = "composite_prop_score",
    refine_seed: int | None = 42,
) -> None:
    if csv_path is None:
        csv_path = _resolve_default_csv()
    else:
        stored_path = store_csv_path(csv_path)
        csv_path = str(stored_path)

    import_result = import_csv(csv_path)
    if not import_result.is_valid:
        print("Import failed:")
        for e in import_result.errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    df = import_result.dataframe
    for w in import_result.warnings:
        print(f"  WARNING: {w}")
    print(f"Loaded {len(df)} bars from {csv_path}")

    strategy = ManualStrategy(DEFAULT_MANUAL_STRATEGY)
    risk = RiskConfig()
    rules = PropRules()

    print("Running historical backtest...")
    bt_result = run_backtest(df, strategy, risk)
    print(f"  Trades: {len(bt_result.trades)}  Net profit: ${bt_result.statistics.net_profit:,.2f}  "
          f"Win rate: {bt_result.statistics.win_rate:.1f}%")

    print("Running prop-firm simulation on historical sequence...")
    trade_pnls = [t.pnl for t in bt_result.trades]
    trade_dates = [t.entry_time for t in bt_result.trades]
    single_run = simulate_account(trade_pnls, trade_dates, rules)
    print(f"  Passed evaluation: {single_run.passed_evaluation}  Reached payout: {single_run.reached_first_payout}")

    if not bt_result.trades:
        print(
            "\nNo trades were generated by this strategy over the given "
            "data -- nothing to run a prop-firm simulation or Monte Carlo "
            "simulation on. Check the strategy's signal logic, or try a "
            "longer/different data range."
        )
        return

    print(f"Running Monte Carlo simulation ({n_sims:,} runs)...")
    mc_cfg = MonteCarloConfig(n_simulations=n_sims)
    mc_result = run_monte_carlo(bt_result.trades, rules, mc_cfg)
    print(f"  Evaluation pass probability: {mc_result.evaluation_pass_probability:.1f}%")
    print(f"  First payout probability: {mc_result.first_payout_probability:.1f}%")
    print(f"  Expected payout: ${mc_result.expected_payout:,.2f}")

    print("Running out-of-sample holdout check...")
    try:
        holdout_comparison = run_holdout_comparison(df, strategy, risk, holdout_frac=0.2)
    except Exception as exc:
        print(f"  Holdout check skipped: {exc}")
        holdout_comparison = None

    period = (str(df["timestamp"].iloc[0]), str(df["timestamp"].iloc[-1]))
    paths = generate_full_report(
        output_dir=output_dir,
        strategy_name=bt_result.strategy_name,
        strategy_source_type=strategy.source_type,
        instrument=Path(csv_path).name,
        timeframe="unknown",
        backtest_period=period,
        backtest_result=bt_result,
        prop_rules=rules,
        prop_single_run=single_run,
        monte_carlo_result=mc_result,
        holdout_comparison=holdout_comparison,
        risk_config=risk,
        price_df=df,
    )
    print("\nReport written to:")
    for k, p in paths.items():
        print(f"  {k}: {p}")

    # ------------------------------------------------------------------
    # Optional: Iterative Refinement. Off unless --refine is passed --
    # everything above this point behaves exactly as it always has.
    # ------------------------------------------------------------------
    if not refine:
        return

    print("\n--- Iterative Refinement (--refine) ---")

    refine_cfg = RefinementConfig(
        fitness_metric=refine_metric,
        population_size=refine_population,
        generations=refine_generations,
        random_seed=refine_seed,
    )
    try:
        result = run_iterative_refinement(
            df, strategy, risk, rules, mc_cfg, refine_cfg, progress_cb=print,
        )
    except RefinementError as exc:
        print(f"  Skipped: {exc}")
        return

    refine_paths = generate_refinement_report(
        output_dir=output_dir,
        result=result,
        strategy_name=bt_result.strategy_name,
        instrument=Path(csv_path).name,
        timeframe="unknown",
        backtest_period=period,
        price_df=df,
    )
    print("\nIterative Refinement report written to:")
    for k, p in refine_paths.items():
        print(f"  {k}: {p}")


def run_search_cli(
    csv_path: str | None,
    output_dir: str,
    mode: str = "family",
    family: str | None = "all",
    max_candidates: int = 500,
    workers: int | None = None,
    min_trades: int = 20,
    min_profit_factor: float = 1.05,
    stage1_top_n: int = 40,
    stage2_top_n: int = 10,
    ga_population: int = 10,
    ga_generations: int = 4,
    full_mc_sims: int = 3000,
    walk_forward_folds: int = 4,
    robustness_neighbors: int = 6,
    fitness_metric: str = "composite_prop_score",
    seed: int = 42,
    db_path: str | None = None,
    promote: bool = True,
) -> None:
    """
    Search Lab: Stages 1-5. Generates a candidate pool (mode="single" wraps
    the same DEFAULT_MANUAL_STRATEGY the rest of --cli uses; mode="family"
    combinatorially expands a named strategy family, or every family if
    `family` is None/"all"), runs it through the cheap filter -> GA
    refinement -> validation gate -> leaderboard funnel, and (by default)
    promotes the champion, if any, through the normal single-strategy
    report pipeline.
    """
    from app.search.batch_runner import SearchStageConfig, promote_champion, run_search
    from app.search.search_report import generate_search_report
    from app.search.strategy_space import generate_search_space, list_families

    if csv_path is None:
        csv_path = _resolve_default_csv()
    else:
        csv_path = str(store_csv_path(csv_path))

    import_result = import_csv(csv_path)
    if not import_result.is_valid:
        print("Import failed:")
        for e in import_result.errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    df = import_result.dataframe
    print(f"Loaded {len(df)} bars from {csv_path}")

    if mode == "family" and family not in (None, "all") and family not in list_families():
        print(f"Unknown family '{family}'. Known families: {list(list_families())}")
        sys.exit(1)

    space = generate_search_space(
        mode=mode,
        family=family,
        single_config=DEFAULT_MANUAL_STRATEGY if mode == "single" else None,
        max_candidates=max_candidates,
        seed=seed,
    )

    stage_cfg = SearchStageConfig(
        min_trades=min_trades, min_profit_factor=min_profit_factor,
        stage1_top_n=stage1_top_n, stage2_top_n=stage2_top_n,
        ga_population=ga_population, ga_generations=ga_generations,
        full_mc_sims=full_mc_sims, walk_forward_folds=walk_forward_folds,
        robustness_neighbors=robustness_neighbors, fitness_metric=fitness_metric,
        workers=workers, random_seed=seed,
    )
    risk = RiskConfig()
    rules = PropRules()
    resolved_db_path = db_path or str(Path(output_dir) / "search.db")

    summary = run_search(
        df, risk, rules, space, stage_cfg, db_path=resolved_db_path,
        instrument=Path(csv_path).name, timeframe="unknown", progress_cb=print,
    )

    report_paths = generate_search_report(
        output_dir=output_dir, summary=summary, space=space,
        instrument=Path(csv_path).name, timeframe="unknown",
    )
    print("\nSearch leaderboard written to:")
    for k, p in report_paths.items():
        print(f"  {k}: {p}")

    if promote and summary.champion_candidate_id:
        print(f"\nPromoting champion candidate {summary.champion_candidate_id} to a full report...")
        promo = promote_champion(
            resolved_db_path, summary.run_id, summary.champion_candidate_id,
            df, risk, rules, output_dir=str(Path(output_dir) / "champion"),
        )
        print("Champion report written to:")
        for k, p in promo["report_paths"].items():
            print(f"  {k}: {p}")
    elif promote:
        print("\nNo champion to promote -- no candidate passed every Stage 3 gate this run.")


def main():
    parser = argparse.ArgumentParser(description="T58 Trading — Prop Algo Backtester")
    parser.add_argument("--cli", action="store_true", help="run headlessly instead of launching the GUI")
    parser.add_argument("--csv", default=None, help="path to a market data CSV (--cli mode); if omitted, uses the "
                                                       "most recently stored dataset in data/raw/, or the bundled sample")
    parser.add_argument("--sims", type=int, default=10000, help="number of Monte Carlo simulations (--cli mode)")
    parser.add_argument("--output", default="reports", help="output directory for the report (--cli mode)")
    parser.add_argument(
        "--refine", action="store_true",
        help="optional: also run Iterative Refinement (genetic-algorithm-style parameter "
             "search) after the normal report, and write a second, separate report. "
             "Off by default -- the normal pipeline is completely unaffected without this "
             "flag. Only applies to the default Manual Strategy Builder DEFAULT_MANUAL_STRATEGY "
             "used by --cli; there is currently no --cli flag to load a custom Manual config.",
    )
    parser.add_argument("--refine-population", type=int, default=10, help="Iterative Refinement: configs per generation")
    parser.add_argument("--refine-generations", type=int, default=5, help="Iterative Refinement: number of generations")
    parser.add_argument(
        "--refine-metric", default="composite_prop_score",
        choices=["composite_prop_score", "eval_pass_probability", "first_payout_probability",
                 "expected_payout", "net_profit", "profit_factor", "sharpe_ratio"],
        help="Iterative Refinement: fitness metric to optimize for",
    )
    parser.add_argument("--refine-seed", type=int, default=42, help="Iterative Refinement: random seed")

    parser.add_argument(
        "--search", action="store_true",
        help="run the Search Lab (Stages 1-5: cheap filter -> GA refinement -> validation gate -> "
             "leaderboard -> champion promotion) instead of the normal single-strategy pipeline.",
    )
    parser.add_argument(
        "--search-mode", default="family", choices=["single", "family"],
        help="'single' re-validates DEFAULT_MANUAL_STRATEGY through the full Stage 1-5 funnel; "
             "'family' generates and searches a combinatorial grid (default).",
    )
    parser.add_argument(
        "--search-family", default="all",
        help="strategy family to search (see app.search.strategy_space.list_families()), or 'all' "
             "to search every family together (default). Ignored when --search-mode=single.",
    )
    parser.add_argument("--search-max-candidates", type=int, default=500,
                         help="cap on how many generated candidates Stage 1 evaluates (random sample if the "
                              "full grid is larger).")
    parser.add_argument("--search-workers", type=int, default=None,
                         help="parallel worker processes for Stages 1-3 (default: all CPU cores).")
    parser.add_argument("--search-min-trades", type=int, default=20,
                         help="Stage 1 cheap filter: minimum trades a candidate must produce to survive.")
    parser.add_argument("--search-min-profit-factor", type=float, default=1.05,
                         help="Stage 1 cheap filter: minimum profit factor a candidate must clear to survive.")
    parser.add_argument("--search-stage1-top-n", type=int, default=40,
                         help="how many Stage 1 survivors advance to Stage 2 (GA refinement).")
    parser.add_argument("--search-stage2-top-n", type=int, default=10,
                         help="how many Stage 2 winners advance to Stage 3 (the validation gate).")
    parser.add_argument("--search-ga-population", type=int, default=10, help="Stage 2 GA population size.")
    parser.add_argument("--search-ga-generations", type=int, default=4, help="Stage 2 GA generations.")
    parser.add_argument("--search-full-mc-sims", type=int, default=3000,
                         help="Monte Carlo simulations per candidate during Stage 3 (full fidelity).")
    parser.add_argument("--search-walk-forward-folds", type=int, default=4,
                         help="Stage 3 walk-forward fold count (0 disables the walk-forward check).")
    parser.add_argument("--search-robustness-neighbors", type=int, default=6,
                         help="Stage 3 parameter-neighborhood perturbation samples (0 disables the check).")
    parser.add_argument(
        "--search-metric", default="composite_prop_score",
        choices=["composite_prop_score", "eval_pass_probability", "first_payout_probability",
                 "expected_payout", "net_profit", "profit_factor", "sharpe_ratio"],
        help="fitness metric used by Stage 2/3.",
    )
    parser.add_argument("--search-seed", type=int, default=42, help="Search Lab: random seed")
    parser.add_argument("--search-db", default=None,
                         help="path to the SQLite results database (default: <output>/search.db)")
    parser.add_argument("--search-no-promote", action="store_true",
                         help="skip Stage 5 (don't auto-promote the champion to a full report).")
    args = parser.parse_args()

    if args.search:
        run_search_cli(
            args.csv, args.output,
            mode=args.search_mode, family=args.search_family,
            max_candidates=args.search_max_candidates, workers=args.search_workers,
            min_trades=args.search_min_trades, min_profit_factor=args.search_min_profit_factor,
            stage1_top_n=args.search_stage1_top_n, stage2_top_n=args.search_stage2_top_n,
            ga_population=args.search_ga_population, ga_generations=args.search_ga_generations,
            full_mc_sims=args.search_full_mc_sims, walk_forward_folds=args.search_walk_forward_folds,
            robustness_neighbors=args.search_robustness_neighbors, fitness_metric=args.search_metric,
            seed=args.search_seed, db_path=args.search_db, promote=not args.search_no_promote,
        )
    elif args.cli:
        run_cli(
            args.csv, args.sims, args.output,
            refine=args.refine,
            refine_population=args.refine_population,
            refine_generations=args.refine_generations,
            refine_metric=args.refine_metric,
            refine_seed=args.refine_seed,
        )
    else:
        launch()


if __name__ == "__main__":
    main()
