"""
T58 Trading — Prop Algo Backtester
Entry point.

Usage:
    python -m app.main                 # launch desktop GUI
    python -m app.main --cli --csv data/examples/EURUSD_5M_sample.csv
                                        # run the full pipeline headlessly
                                        # (useful on machines without a display,
                                        # and for scripted/CI runs)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from app.backtest.engine import run_backtest, run_holdout_comparison
from app.backtest.risk import RiskConfig
from app.data.importer import import_csv
from app.data.storage import list_stored_datasets, store_csv_path
from app.monte_carlo.engine import MonteCarloConfig, run_monte_carlo
from app.optimize.parameter_space import RefinementError
from app.optimize.refinement import RefinementConfig, run_iterative_refinement
from app.prop.simulator import PropRules, simulate_account
from app.reports.generator import generate_full_report
from app.reports.refinement_report import generate_refinement_report
from app.strategy.manual import ManualStrategy
from app.ui.main_window import launch

DEFAULT_MANUAL_STRATEGY = {
    "name": "SMA 20/50 Cross",
    "indicators": [
        {"type": "sma", "period": 20, "column": "close", "as": "sma_fast"},
        {"type": "sma", "period": 50, "column": "close", "as": "sma_slow"},
    ],
    "long_entry": "sma_fast > sma_slow",
    "long_exit": "sma_fast < sma_slow",
    "short_entry": "sma_fast < sma_slow",
    "short_exit": "sma_fast > sma_slow",
    "stop_loss_pips": 20,
    "take_profit_pips": 40,
}


def _resolve_default_csv() -> str:
    """Prefer a dataset already stored in data/raw/ over the bundled example."""
    stored = list_stored_datasets()
    if stored:
        return str(stored[0].path)  # most recently added
    return "data/examples/EURUSD_5M_sample.csv"


def run_cli(
    csv_path: str | None,
    n_sims: int,
    output_dir: str,
    refine: bool = False,
    refine_population: int = 10,
    refine_generations: int = 5,
    refine_metric: str = "composite_prop_score",
    refine_seed: int | None = 42,
) -> None:
    if csv_path is None:
        csv_path = _resolve_default_csv()
    else:
        stored_path = store_csv_path(csv_path)
        csv_path = str(stored_path)

    import_result = import_csv(csv_path)
    if not import_result.is_valid:
        print("Import failed:")
        for e in import_result.errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    df = import_result.dataframe
    for w in import_result.warnings:
        print(f"  WARNING: {w}")
    print(f"Loaded {len(df)} bars from {csv_path}")

    strategy = ManualStrategy(DEFAULT_MANUAL_STRATEGY)
    risk = RiskConfig()
    rules = PropRules()

    print("Running historical backtest...")
    bt_result = run_backtest(df, strategy, risk)
    print(f"  Trades: {len(bt_result.trades)}  Net profit: ${bt_result.statistics.net_profit:,.2f}  "
          f"Win rate: {bt_result.statistics.win_rate:.1f}%")

    print("Running prop-firm simulation on historical sequence...")
    trade_pnls = [t.pnl for t in bt_result.trades]
    trade_dates = [t.entry_time for t in bt_result.trades]
    single_run = simulate_account(trade_pnls, trade_dates, rules)
    print(f"  Passed evaluation: {single_run.passed_evaluation}  Reached payout: {single_run.reached_first_payout}")

    if not bt_result.trades:
        print(
            "\nNo trades were generated by this strategy over the given "
            "data -- nothing to run a prop-firm simulation or Monte Carlo "
            "simulation on. Check the strategy's signal logic, or try a "
            "longer/different data range."
        )
        return

    print(f"Running Monte Carlo simulation ({n_sims:,} runs)...")
    mc_cfg = MonteCarloConfig(n_simulations=n_sims)
    mc_result = run_monte_carlo(bt_result.trades, rules, mc_cfg)
    print(f"  Evaluation pass probability: {mc_result.evaluation_pass_probability:.1f}%")
    print(f"  First payout probability: {mc_result.first_payout_probability:.1f}%")
    print(f"  Expected payout: ${mc_result.expected_payout:,.2f}")

    print("Running out-of-sample holdout check...")
    try:
        holdout_comparison = run_holdout_comparison(df, strategy, risk, holdout_frac=0.2)
    except Exception as exc:
        print(f"  Holdout check skipped: {exc}")
        holdout_comparison = None

    period = (str(df["timestamp"].iloc[0]), str(df["timestamp"].iloc[-1]))
    paths = generate_full_report(
        output_dir=output_dir,
        strategy_name=bt_result.strategy_name,
        strategy_source_type=strategy.source_type,
        instrument=Path(csv_path).name,
        timeframe="unknown",
        backtest_period=period,
        backtest_result=bt_result,
        prop_rules=rules,
        prop_single_run=single_run,
        monte_carlo_result=mc_result,
        holdout_comparison=holdout_comparison,
        risk_config=risk,
        price_df=df,
    )
    print("\nReport written to:")
    for k, p in paths.items():
        print(f"  {k}: {p}")

    # ------------------------------------------------------------------
    # Optional: Iterative Refinement. Off unless --refine is passed --
    # everything above this point behaves exactly as it always has.
    # ------------------------------------------------------------------
    if not refine:
        return

    print("\n--- Iterative Refinement (--refine) ---")

    refine_cfg = RefinementConfig(
        fitness_metric=refine_metric,
        population_size=refine_population,
        generations=refine_generations,
        random_seed=refine_seed,
    )
    try:
        result = run_iterative_refinement(
            df, strategy, risk, rules, mc_cfg, refine_cfg, progress_cb=print,
        )
    except RefinementError as exc:
        print(f"  Skipped: {exc}")
        return

    refine_paths = generate_refinement_report(
        output_dir=output_dir,
        result=result,
        strategy_name=bt_result.strategy_name,
        instrument=Path(csv_path).name,
        timeframe="unknown",
        backtest_period=period,
        price_df=df,
    )
    print("\nIterative Refinement report written to:")
    for k, p in refine_paths.items():
        print(f"  {k}: {p}")


def main():
    parser = argparse.ArgumentParser(description="T58 Trading — Prop Algo Backtester")
    parser.add_argument("--cli", action="store_true", help="run headlessly instead of launching the GUI")
    parser.add_argument("--csv", default=None, help="path to a market data CSV (--cli mode); if omitted, uses the "
                                                       "most recently stored dataset in data/raw/, or the bundled sample")
    parser.add_argument("--sims", type=int, default=10000, help="number of Monte Carlo simulations (--cli mode)")
    parser.add_argument("--output", default="reports", help="output directory for the report (--cli mode)")
    parser.add_argument(
        "--refine", action="store_true",
        help="optional: also run Iterative Refinement (genetic-algorithm-style parameter "
             "search) after the normal report, and write a second, separate report. "
             "Off by default -- the normal pipeline is completely unaffected without this "
             "flag. Only applies to the default Manual Strategy Builder DEFAULT_MANUAL_STRATEGY "
             "used by --cli; there is currently no --cli flag to load a custom Manual config.",
    )
    parser.add_argument("--refine-population", type=int, default=10, help="Iterative Refinement: configs per generation")
    parser.add_argument("--refine-generations", type=int, default=5, help="Iterative Refinement: number of generations")
    parser.add_argument(
        "--refine-metric", default="composite_prop_score",
        choices=["composite_prop_score", "eval_pass_probability", "first_payout_probability",
                 "expected_payout", "net_profit", "profit_factor", "sharpe_ratio"],
        help="Iterative Refinement: fitness metric to optimize for",
    )
    parser.add_argument("--refine-seed", type=int, default=42, help="Iterative Refinement: random seed")
    args = parser.parse_args()

    if args.cli:
        run_cli(
            args.csv, args.sims, args.output,
            refine=args.refine,
            refine_population=args.refine_population,
            refine_generations=args.refine_generations,
            refine_metric=args.refine_metric,
            refine_seed=args.refine_seed,
        )
    else:
        launch()


if __name__ == "__main__":
    main()
